#ifndef SORTFILTERPROXYMODEL_GLOBAL_H
#define SORTFILTERPROXYMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SORTFILTERPROXYMODEL_LIBRARY)
#  define SORTFILTERPROXYMODEL_EXPORT Q_DECL_EXPORT
#else
#  define SORTFILTERPROXYMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // SORTFILTERPROXYMODEL_GLOBAL_H
