#ifndef AUDIOSTREAMINGLIB_GLOBAL_H
#define AUDIOSTREAMINGLIB_GLOBAL_H

#include <QtGlobal>

#if defined(AUDIOSTREAMING_LIBRARY)
#  define AUDIOSTREAMING_LIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define AUDIOSTREAMING_LIBRARY_EXPORT Q_DECL_IMPORT
#endif



#endif // AUDIOSTREAMINGLIB_GLOBAL_H
